### ISSUE TITLE
Morning session: Peer to peer code review

### ISSUE THREAD

**Issue by Ursaaaaaa** [GedeonTS/Artficial-intelligence-forum#2]
Hi @GedeonTS 
Great job on completing your Awesome Books project! Outstanding work! 👏🏼🔥

Highlights 🥳
No linter errors ✔️
Great job writing clean code. 🔥

**Optional Changes**

You can use a `<article> `tag in instead of a `<div> `tag for cards.

**Comment by GedeonTS** [comment]
Thank you! @ramrod433
