### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by Pazzo97** [GedeonTS/Artficial-intelligence-forum#3]
- Kindly start the page with h1 headings instead of h3.
- Please consider putting divs inside the sections instead of sections inside divs.
- Please use divs inside the section instead of sections inside sections.
- For good practice try to avoid <br/> tags and divide your paragraphs into two <p> tags.
- Please consider using of <bold> and <u> tags should be applied in the CSS by use of font-weight and text-decoration: underline.

**Comment by GedeonTS** [comment]
Thank you! @Pazzo97
